import type { ServiceListing } from "../_components/service-listing-card"

export const allListings: ServiceListing[] = [
  {
    id: "1",
    image: "/services/venue-garden.jpg",
    name: "Rose Garden Estate",
    category: "Venues",
    rating: 4.9,
    reviewCount: 137,
    location: "Meadow Hills, Countryside",
    priceRange: "$3,500",
    description: "A stunning outdoor garden venue surrounded by rose bushes and ancient oak trees. Perfect for intimate and grand weddings alike.",
    isVerified: true,
    isFavorited: false,
    tags: ["Outdoor", "Garden", "Up to 300 guests"],
  },
  {
    id: "2",
    image: "/services/venue-ballroom.jpg",
    name: "Grand Ballroom Venue",
    category: "Venues",
    rating: 4.8,
    reviewCount: 89,
    location: "Downtown, City Center",
    priceRange: "$6,000",
    description: "An opulent ballroom with crystal chandeliers, marble floors, and world-class staff to make your celebration unforgettable.",
    isVerified: true,
    isFavorited: true,
    tags: ["Indoor", "Luxury", "Up to 500 guests"],
  },
  {
    id: "3",
    image: "/services/photographer-portrait.jpg",
    name: "Elegant Events Photography",
    category: "Photography",
    rating: 4.9,
    reviewCount: 215,
    location: "Available Citywide",
    priceRange: "$2,500",
    description: "Award-winning wedding photography that captures every emotion. Candid and editorial styles with a quick turnaround time.",
    isVerified: true,
    isFavorited: false,
    tags: ["Candid", "Editorial", "Drone shots"],
  },
  {
    id: "4",
    image: "/services/catering-elegant.jpg",
    name: "Gourmet Catering Co.",
    category: "Catering",
    rating: 4.7,
    reviewCount: 174,
    location: "Serves all areas",
    priceRange: "$75/person",
    description: "Exquisite multi-course menus crafted by our Michelin-trained chefs. From hors d'oeuvres to custom wedding cakes.",
    isVerified: true,
    isFavorited: false,
    tags: ["Fine Dining", "Custom Menus", "Allergies-friendly"],
  },
  {
    id: "5",
    image: "/services/band-live.jpg",
    name: "Harmony Wedding Band",
    category: "Entertainment",
    rating: 4.8,
    reviewCount: 96,
    location: "Available Nationwide",
    priceRange: "$3,200",
    description: "A 7-piece live band specializing in wedding receptions. From jazz cocktail hours to dance floor hits that keep guests moving.",
    isVerified: false,
    isFavorited: false,
    tags: ["Live Band", "DJ option", "Ceremony music"],
  },
  {
    id: "6",
    image: "/services/decoration-floral.jpg",
    name: "Bloom & Petal Designs",
    category: "Decorations",
    rating: 4.9,
    reviewCount: 128,
    location: "Metro Area",
    priceRange: "$1,800",
    description: "Bespoke floral arrangements and venue styling. From romantic centerpieces to breathtaking ceremony arches.",
    isVerified: true,
    isFavorited: true,
    tags: ["Floral Design", "Venue Styling", "Custom themes"],
  },
  {
    id: "7",
    image: "/services/planner-working.jpg",
    name: "Dream Day Planners",
    category: "Planning",
    rating: 5.0,
    reviewCount: 64,
    location: "City & Suburbs",
    priceRange: "$4,500",
    description: "Full-service wedding planning from start to finish. We handle every detail so you can enjoy the journey to your big day.",
    isVerified: true,
    isFavorited: false,
    tags: ["Full Service", "Day-of Coordination", "Budget-friendly"],
  },
  {
    id: "8",
    image: "/services/venue-beach.jpg",
    name: "Coastal Bliss Weddings",
    category: "Venues",
    rating: 4.7,
    reviewCount: 52,
    location: "Sunset Beach, Coast",
    priceRange: "$4,200",
    description: "Say your vows with the ocean as your backdrop. Beachfront ceremonies and tented receptions with stunning sunset views.",
    isVerified: false,
    isFavorited: false,
    tags: ["Beach", "Outdoor", "Up to 200 guests"],
  },
]
